name = "tabriz-portfolio"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "tabriz-latifov-portfolio-db"
database_id = "f1f90679-2a9a-4466-aa78-10a241895044"
migrations_dir = "drizzle"
